CREATE TABLE MEMBER (
    MEMBER_NO BIGINT PRIMARY KEY,
    MEMBER_ID VARCHAR(255),
    NAME VARCHAR(255),
    BIRTH_YEAR CHAR(4),
    PASSWORD VARCHAR(255),
    INSERT_DATE DATE,
    UPDATE_DATE DATE
);

CREATE TABLE SCHOOL (
    SCHOOL_NO BIGINT PRIMARY KEY,
    SCHOOL_NAME VARCHAR(255),
    SCHOOL_TYPE_CODE INTEGER, -- 1 초등학교 / 2 중학교 / 3 고등학교
    INSERT_DATE DATE,
    UPDATE_DATE DATE
);

CREATE TABLE ALUMNI (
    MEMBER_NO BIGINT,
    SCHOOL_NO BIGINT,
    INSERT_DATE DATE,
    UPDATE_DATE DATE,
    PRIMARY KEY (MEMBER_NO, SCHOOL_NO)
);

CREATE TABLE CODE (
    CODE INTEGER,
    CODE_NAME VARCHAR(255),
    INSERT_DATE DATE,
    UPDATE_DATE DATE
);